version: "3.7"
services:
  web:
    build: .
    command: npm run production
    container_name: covid19tu-network-docker-production
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next